
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  AztecAddress,
  AztecAddressLike,
  CompleteAddress,
  Contract,
  ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  ContractMethod,
  DeployMethod,
  EthAddress,
  EthAddressLike,
  FieldLike,
  Fr,
  Point,
  PublicKey,
  Wallet,
} from '@aztec/aztec.js';
import DicesContractArtifactJson from './Dices.json' assert { type: 'json' };
export const DicesContractArtifact = DicesContractArtifactJson as ContractArtifact;

/**
 * Type-safe interface for contract Dices;
 */
export class DicesContract extends ContractBase {
  
  private constructor(
    completeAddress: CompleteAddress,
    wallet: Wallet,
    portalContract = EthAddress.ZERO
  ) {
    super(completeAddress, DicesContractArtifact, wallet, portalContract);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, DicesContract.artifact, wallet) as Promise<DicesContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<DicesContract>(Point.ZERO, wallet, DicesContractArtifact, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public key to derive the address.
   */
  public static deployWithPublicKey(publicKey: PublicKey, wallet: Wallet, ) {
    return new DeployMethod<DicesContract>(publicKey, wallet, DicesContractArtifact, Array.from(arguments).slice(2));
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return DicesContractArtifact;
  }
  

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public methods!: {
    
    /** _roll(diceId: field, seed: field) */
    _roll: ((diceId: FieldLike, seed: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_nullifier(_: field, _: field, _: field, _: array) */
    compute_note_hash_and_nullifier: ((_: FieldLike, _: FieldLike, _: FieldLike, _: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** dice(addr: field, game_id: integer) */
    dice: ((addr: FieldLike, game_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** readDice(addr: field, game_id: integer) */
    readDice: ((addr: FieldLike, game_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** roll(game_id: integer, seed: integer) */
    roll: ((game_id: (bigint | number), seed: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };
}
